---
mywin1:
 hosts:
  winhost:
   ansible_user: adminuser
   ansible_password: winSRV@12345
   ansible_winrm_transport: ntlm
   ansible_connection: winrm
   ansible_port: 5985
   ansible_winrm_server_cert_validation: ignore
 vars:
   
...